name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set executable permissions
      run: |
        chmod +x install-deps.sh
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add install-deps.sh
        git commit -m "Set executable permissions for install-deps.sh"
        git push

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
